width = 780
height = 540

background = "rgba(5, 9, 13, 0.82)"
text_color = "#D5E5EA"
comment_color = "#71838A"

selected_color = "rgba(39, 215, 237, 0.24)"
hover_color = "rgba(103, 236, 255, 0.055)"
border_color = "rgba(103, 236, 255, 0.13)"

border_radius = 22
border_width = 1

font = "JetBrainsMono Nerd Font"

app_font_size = 15
comment_font_size = 11
search_font_size = 17

search_placeholder = "Search applications..."

show_icons = true
show_comments = true
icon_size = 42

row_radius = 13
row_margin = 2

search_background = "rgba(8, 18, 23, 0.82)"
search_border_color = "rgba(103, 236, 255, 0.09)"
search_focus_border_color = "rgba(53, 232, 255, 0.70)"